### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by huangsijun17** [simonbru/nextboot#1]
1. Is it possible to modify a GUI version using Tkinter for handheld game consoles and tablets?
2. Can you tell me the license of the software?

**Comment by simonbru** [comment]
Hello!

1. I have not used Tkinter, but it sounds doable. You can probably do this by re-implementing the `choose_entry` function for Tkinter.

2. I just set an MIT license for the project and uploaded a LICENSE file for clarification. :)

**Comment by huangsijun17** [comment]
Thanks for replying.
